version: "3"

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    networks:
      - network
    ports:
      - "6379:6379"

networks:
  network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
